from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("recommend/", views.recommend, name="recommend"),
    path("profile/<int:profile_id>/popup/", views.profile_popup, name="profile_popup"),
    path("movies-tv/<str:category>/", views.discover, {"media_type": "movie_tv"}, name="movies_tv"),
    path("anime/<str:category>/", views.discover, {"media_type": "anime"}, name="anime"),
    path("movies-tv/collections/<int:collection_id>/", views.collection_detail, name="collection_detail"),
    path("search/", views.search, name="search"),
    path("titles/<int:pk>/", views.title_detail, name="title_detail"),
    path("titles/<int:pk>/episodes/", views.title_episodes, name="title_episodes"),
    path("titles/<int:pk>/mark-watched/", views.title_mark_watched, name="title_mark_watched"),
    path("titles/<int:pk>/unmark-watched/", views.title_unmark_watched, name="title_unmark_watched"),
    path("titles/<int:pk>/unmark-last-watched/", views.title_unmark_last_watched, name="title_unmark_last_watched"),
    path(
        "titles/<int:pk>/episodes/<int:season>/<int:episode_number>/mark-watched/",
        views.episode_mark_watched,
        name="episode_mark_watched",
    ),
    path("titles/<int:pk>/rate/", views.title_rate, name="title_rate"),
    path("titles/<int:pk>/recommend/", views.send_recommendation, name="send_recommendation"),
    path("recommendations/<int:pk>/dismiss/", views.dismiss_recommendation, name="dismiss_recommendation"),
    path(
        "recommendations/<int:pk>/add-to-watchlist/",
        views.add_recommendation_to_watchlist,
        name="add_recommendation_to_watchlist",
    ),
    path("titles/preview/<str:media_type>/<int:tmdb_id>/", views.title_preview, name="title_preview"),
    path(
        "titles/preview/<str:media_type>/<int:tmdb_id>/episodes/",
        views.title_preview_episodes,
        name="title_preview_episodes",
    ),
    path(
        "titles/preview/<str:media_type>/<int:tmdb_id>/add-to-watchlist/",
        views.title_preview_add_to_watchlist,
        name="title_preview_add_to_watchlist",
    ),
    path(
        "titles/preview/<str:media_type>/<int:tmdb_id>/mark-watched/",
        views.title_preview_mark_watched,
        name="title_preview_mark_watched",
    ),
    path(
        "titles/preview/<str:media_type>/<int:tmdb_id>/lists/<int:list_id>/add/",
        views.title_preview_add_to_list,
        name="title_preview_add_to_list",
    ),
    path(
        "titles/preview/<str:media_type>/<int:tmdb_id>/recommend/",
        views.title_preview_send_recommendation,
        name="title_preview_send_recommendation",
    ),
    path("history/", views.history, name="history"),
    path("profile/<int:profile_id>/history/", views.history, name="member_history"),
    path("history/bulk-delete/", views.history_bulk_delete, name="history_bulk_delete"),
    path("history/delete-episode/<int:event_id>/", views.history_delete_episode, name="history_delete_episode"),
    path("calendar/", views.calendar_view, name="calendar"),
    path("lists/", views.lists, name="lists"),
    path("lists/create/", views.create_list, name="create_list"),
    path("lists/<int:list_id>/", views.list_detail, name="list_detail"),
    path("lists/<int:list_id>/delete/", views.delete_list, name="delete_list"),
    path("lists/<int:list_id>/add/", views.add_to_list, name="add_to_list"),
    path("lists/<int:list_id>/remove/", views.remove_from_list, name="remove_from_list"),
    path("lists/<int:list_id>/search-titles/", views.search_titles, name="search_titles"),
    path("stats/", views.stats, name="stats"),
    path("stats/heatmap/", views.stats_heatmap, name="stats_heatmap"),
    path("profile/<int:profile_id>/stats/", views.stats, name="member_stats"),
    path("profile/<int:profile_id>/stats/heatmap/", views.stats_heatmap, name="member_stats_heatmap"),
    path("activity/", views.activity, name="activity"),
    path("settings/", views.settings_view, name="settings"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("settings/profile/create/", views.create_profile, name="create_profile"),
    path("settings/profile/<int:profile_id>/delete/", views.delete_profile, name="delete_profile"),
    path("settings/profile/<int:profile_id>/promote/", views.promote_to_owner, name="promote_to_owner"),
    path("settings/profile/<int:profile_id>/demote/", views.demote_from_owner, name="demote_from_owner"),
    path("settings/appearance/", views.save_appearance, name="save_appearance"),
    path("settings/privacy/", views.save_privacy, name="save_privacy"),
    path("settings/notifications/", views.save_notifications, name="save_notifications"),
    path("settings/integrations/", views.save_instance_config, name="save_instance_config"),
    path("settings/sync-log/", views.sync_log, name="sync_log"),
    path("export/csv/", views.export_csv, name="export_csv"),
    path("export/trakt-json/", views.export_trakt_json, name="export_trakt_json"),
    path("notifications/", views.notifications_panel, name="notifications_panel"),
    path("notifications/<int:pk>/read/", views.mark_notification_read, name="mark_notification_read"),
    path("notifications/read-all/", views.mark_all_notifications_read, name="mark_all_notifications_read"),
    path("change-credentials/", views.change_credentials, name="change_credentials"),
    path("profile/", views.my_profile, name="my_profile"),
    path("profile/delete/", views.delete_own_account, name="delete_own_account"),
    path("import/trakt/connect/", views.oauth_connect, {"provider": "trakt"}, name="trakt_connect"),
    path("import/trakt/callback/", views.oauth_callback, {"provider": "trakt"}, name="trakt_callback"),
    path("import/simkl/connect/", views.oauth_connect, {"provider": "simkl"}, name="simkl_connect"),
    path("import/simkl/callback/", views.oauth_callback, {"provider": "simkl"}, name="simkl_callback"),
    path("settings/sync-schedule/<str:provider>/", views.save_sync_schedule, name="save_sync_schedule"),
    path("settings/sync-now/<str:provider>/", views.trigger_manual_sync, name="trigger_manual_sync"),
    path("settings/disconnect/<str:provider>/", views.disconnect_provider, name="disconnect_provider"),
    path(
        "settings/disconnect-and-wipe/<str:provider>/",
        views.disconnect_and_wipe_provider,
        name="disconnect_and_wipe_provider",
    ),
    path("settings/clear-watch-history/", views.clear_watch_history, name="clear_watch_history"),
    path("import/csv/", views.import_csv_upload, name="import_csv"),
    path("import/csv/preview/", views.import_csv_preview, name="import_csv_preview"),
    path("import/csv/remap/", views.import_csv_remap, name="import_csv_remap"),
    path("import/csv/cancel/", views.import_csv_cancel, name="import_csv_cancel"),
    path("import/csv/commit/", views.import_csv_commit, name="import_csv_commit"),
    path("import/csv/result/", views.import_csv_result, name="import_csv_result"),
    path("accounts/login/", views.SpoolLoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
]
