# Generated by Django 5.1.15 on 2026-07-08 20:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('episode', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['title', 'season', 'episode'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('avatar_color', models.CharField(default='#3a2a1c', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV'), ('anime', 'Anime')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('poster_url', models.URLField(blank=True)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='tracker.genre')),
            ],
            options={
                'ordering': ['name', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(choices=[('episode', 'New episode'), ('season_premiere', 'Season premiere'), ('movie_release', 'Movie release')], max_length=20)),
                ('release_date', models.DateTimeField()),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='tracker.episode')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='tracker.title')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('imdb', 'IMDb'), ('rt', 'Rotten Tomatoes'), ('trakt', 'Trakt')], max_length=20)),
                ('score', models.CharField(max_length=10)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tracker.title')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tracker.title'),
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField()),
                ('is_rewatch', models.BooleanField(default=False)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_events', to='tracker.episode')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='tracker.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='tracker.title')),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='tracker.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WatchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='tracker.title')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.watchlist')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('planned', 'Planned')], max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.episode')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='tracker.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='tracker.title')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['media_type'], name='tracker_tit_media_t_56930c_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseschedule',
            index=models.Index(fields=['release_date'], name='tracker_rel_release_5cedd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='releaseschedule',
            constraint=models.UniqueConstraint(fields=('title', 'episode', 'release_type'), name='unique_release_per_title_episode_type'),
        ),
        migrations.AddConstraint(
            model_name='externalrating',
            constraint=models.UniqueConstraint(fields=('title', 'source'), name='unique_rating_source_per_title'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('title', 'season', 'episode'), name='unique_episode_per_title'),
        ),
        migrations.AddIndex(
            model_name='watchevent',
            index=models.Index(fields=['profile', 'watched_at'], name='tracker_wat_profile_094425_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(fields=('watchlist', 'title'), name='unique_title_per_watchlist'),
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(fields=('profile', 'title'), name='unique_progress_per_profile_title'),
        ),
    ]
