# Generated by Django 5.1.15 on 2026-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='runtime_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='runtime_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('planned', 'Planned'), ('completed', 'Completed')], max_length=12),
        ),
    ]
