# Generated by Django 5.1.15 on 2026-07-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_episode_runtime_minutes_title_runtime_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_format',
            field=models.CharField(choices=[('12h', '12-hour (AM/PM)'), ('24h', '24-hour')], default='12h', max_length=3),
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('trakt', 'Trakt'), ('simkl', 'Simkl')], max_length=10)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='tracker.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'provider'), name='unique_provider_per_profile')],
            },
        ),
    ]
