# Generated by Django 5.1.15 on 2026-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile_time_format_externalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trakt_client_id', models.CharField(blank=True, max_length=255)),
                ('trakt_client_secret', models.CharField(blank=True, max_length=255)),
                ('simkl_client_id', models.CharField(blank=True, max_length=255)),
                ('simkl_client_secret', models.CharField(blank=True, max_length=255)),
                ('tmdb_api_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
