# Generated by Django 5.1.15 on 2026-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_instanceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
