# Generated by Django 5.1.15 on 2026-07-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_profile_must_change_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('trakt', 'Trakt'), ('simkl', 'Simkl')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('item_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tracker.profile')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['profile', '-started_at'], name='tracker_syn_profile_66b32f_idx')],
            },
        ),
    ]
