# Generated by Django 5.1.15 on 2026-07-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
