# Generated by Django 5.1.15 on 2026-07-10 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_externalaccount_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='sync_hour',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='sync_interval_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='sync_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
    ]
