# Generated by Django 5.1.15 on 2026-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_externalaccount_sync_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='import_lists',
            field=models.BooleanField(default=False),
        ),
    ]
