# Generated by Django 5.1.15 on 2026-07-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_externalaccount_import_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
