# Generated by Django 5.1.15 on 2026-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_flag_existing_watchlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_landing_page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('movies_tv', 'Movies & TV'), ('anime', 'Anime'), ('history', 'History'), ('calendar', 'Calendar'), ('lists', 'Lists'), ('stats', 'Stats')], default='dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='share_activity',
            field=models.BooleanField(default=True),
        ),
    ]
