# Generated by Django 5.1.15 on 2026-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_profile_notify_new_releases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
