# Generated by Django 5.1.15 on 2026-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_externalaccount_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
