# Generated by Django 5.1.15 on 2026-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_profile_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='latest_known_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_release', 'New release'), ('upcoming_release', 'Upcoming release'), ('sync_failed', 'Sync failed'), ('system_update', 'System update')], max_length=20),
        ),
    ]
