# Generated by Django 5.1.15 on 2026-07-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_instanceconfig_latest_known_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_release', 'New release'), ('upcoming_release', 'Upcoming release'), ('sync_failed', 'Sync failed'), ('system_update', 'System update'), ('recommendation_watched', 'Recommendation watched')], max_length=25),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('watched', 'Watched'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_recommendations', to='tracker.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='tracker.title')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to='tracker.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_profile', 'to_profile', 'title'), name='unique_pending_recommendation')],
            },
        ),
    ]
