# Generated by Django 5.1.15 on 2026-07-20 17:11

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_notification_kind_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(default=tracker.models.random_avatar_color, max_length=7),
        ),
    ]
