# Generated by Django 5.1.15 on 2026-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_profile_avatar_image_alter_profile_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_release', 'New release'), ('upcoming_release', 'Upcoming release'), ('sync_failed', 'Sync failed'), ('system_update', 'System update'), ('recommendation_received', 'Recommendation received'), ('recommendation_watched', 'Recommendation watched')], max_length=25),
        ),
    ]
