# Generated by Django 5.1.15 on 2026-07-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
