# Generated by Django 5.1.15 on 2026-07-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='AdminAuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('profile_created', 'Profile created'), ('profile_removed', 'Profile removed'), ('profile_promoted', 'Promoted to owner'), ('profile_self_deleted', 'Deleted own account')], max_length=30)),
                ('target_display_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries_as_actor', to='tracker.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
