# Generated by Django 5.1.15 on 2026-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_profile_timezone_adminauditlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlogentry',
            name='action',
            field=models.CharField(choices=[('profile_created', 'Profile created'), ('profile_removed', 'Profile removed'), ('profile_promoted', 'Promoted to owner'), ('profile_demoted', 'Demoted to member'), ('profile_self_deleted', 'Deleted own account')], max_length=30),
        ),
    ]
