# Generated by Django 5.1.15 on 2026-07-27 11:18

from django.db import migrations, models


def backfill_position(apps, schema_editor):
    """Seeds position from each watchlist's pre-migration visible order
    (newest-added first, the old default ordering) so existing lists don't
    visibly reshuffle the moment this ships - position just becomes the
    new name for the order they were already in."""
    WatchList = apps.get_model("tracker", "WatchList")
    WatchListItem = apps.get_model("tracker", "WatchListItem")
    for watchlist_id in WatchList.objects.values_list("id", flat=True):
        items = WatchListItem.objects.filter(watchlist_id=watchlist_id).order_by("-added_at")
        for index, item in enumerate(items):
            item.position = index
            item.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_profile_last_seen_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_position, migrations.RunPython.noop),
    ]
