# Generated by Django 5.1.15 on 2026-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_alter_watchlistitem_options_watchlist_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrating',
            name='source',
            field=models.CharField(choices=[('imdb', 'IMDb'), ('rt', 'Rotten Tomatoes'), ('trakt', 'Trakt'), ('mal', 'MAL')], max_length=20),
        ),
    ]
