# Generated by Django 5.1.15 on 2026-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_alter_externalrating_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discover_watched_display',
            field=models.CharField(choices=[('show', 'Show'), ('dim', 'Dim'), ('hide', 'Hide')], default='show', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='discover_watchlisted_display',
            field=models.CharField(choices=[('show', 'Show'), ('dim', 'Dim'), ('hide', 'Hide')], default='show', max_length=4),
        ),
    ]
