# Generated by Django 5.1.15 on 2026-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_datalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=10),
        ),
    ]
