# Generated by Django 5.1.15 on 2026-07-31 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_alter_datalog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='provider',
            field=models.CharField(choices=[('trakt', 'Trakt'), ('simkl', 'Simkl'), ('nuvio', 'Nuvio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='provider',
            field=models.CharField(choices=[('trakt', 'Trakt'), ('simkl', 'Simkl'), ('nuvio', 'Nuvio')], max_length=10),
        ),
        migrations.CreateModel(
            name='NuvioConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('encrypted_refresh_token', models.TextField()),
                ('nuvio_profile_id', models.PositiveSmallIntegerField()),
                ('nuvio_profile_name', models.CharField(blank=True, max_length=100)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_interval_days', models.PositiveSmallIntegerField(default=1)),
                ('sync_hour', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(23)])),
                ('sync_minute', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)])),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nuvio_connection', to='tracker.profile')),
            ],
        ),
    ]
