# Generated by Django 5.1.15 on 2026-07-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_alter_externalaccount_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='action',
            field=models.CharField(choices=[('import', 'CSV Import'), ('export', 'Export'), ('trakt_connect', 'Trakt Connect'), ('simkl_connect', 'Simkl Connect'), ('nuvio_connect', 'Nuvio Connect')], max_length=15),
        ),
    ]
