# Generated by Django 5.1.15 on 2026-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_alter_datalog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchevent',
            name='source',
            field=models.CharField(blank=True, choices=[('nuvio', 'Nuvio')], default='', max_length=20),
        ),
    ]
