# Generated by Django 5.2.16 on 2026-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_title_name_trigram_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlogentry',
            name='action',
            field=models.CharField(choices=[('profile_created', 'Profile created'), ('profile_removed', 'Profile removed'), ('profile_promoted', 'Promoted to owner'), ('profile_demoted', 'Demoted to member'), ('profile_self_deleted', 'Deleted own account'), ('profile_password_reset', 'Password reset')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='action',
            field=models.CharField(choices=[('import', 'CSV Import'), ('export', 'Export'), ('trakt_connect', 'Trakt Connect'), ('simkl_connect', 'Simkl Connect'), ('nuvio_connect', 'Nuvio Connect'), ('merge_duplicates', 'Merge Duplicate Titles'), ('backfill_posters', 'Backfill Posters'), ('backfill_genres', 'Backfill Genres'), ('backfill_completion', 'Backfill Completion'), ('backfill_rewatches', 'Backfill Rewatches')], max_length=20),
        ),
    ]
