# Generated by Django 5.2.16 on 2026-08-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_admin_maintenance_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='log_retention_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
