# Generated by Django 5.2.16 on 2026-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_log_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='provider',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='action',
            field=models.CharField(choices=[('import', 'CSV Import'), ('export', 'Export'), ('trakt_connect', 'Trakt Connect'), ('simkl_connect', 'Simkl Connect'), ('nuvio_connect', 'Nuvio Connect'), ('merge_duplicates', 'Merge Duplicate Titles'), ('backfill_posters', 'Backfill Posters'), ('backfill_genres', 'Backfill Genres'), ('backfill_completion', 'Backfill Completion'), ('backfill_rewatches', 'Backfill Rewatches'), ('disconnect', 'Disconnect')], max_length=20),
        ),
    ]
