# Generated by Django 5.2.16 on 2026-08-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_log_provider_and_disconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='encrypted_mdblist_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='mdblist_quota_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='mdblist_quota_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='mdblist_quota_pause_logged_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='mdblist_rate_limit_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='action',
            field=models.CharField(choices=[('import', 'CSV Import'), ('export', 'Export'), ('trakt_connect', 'Trakt Connect'), ('simkl_connect', 'Simkl Connect'), ('nuvio_connect', 'Nuvio Connect'), ('merge_duplicates', 'Merge Duplicate Titles'), ('backfill_posters', 'Backfill Posters'), ('backfill_genres', 'Backfill Genres'), ('backfill_completion', 'Backfill Completion'), ('backfill_rewatches', 'Backfill Rewatches'), ('disconnect', 'Disconnect'), ('mdblist_refresh', 'MDBList Refresh')], max_length=20),
        ),
        migrations.CreateModel(
            name='TitleRatingsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.JSONField(blank=True, default=list)),
                ('fetch_attempted', models.BooleanField(default=False)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('next_refresh_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_cache', to='tracker.title')),
            ],
        ),
    ]
