# Generated by Django 5.2.16 on 2026-08-12 10:02

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_instanceconfig_encrypted_mdblist_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchevent',
            name='source',
            field=models.CharField(blank=True, choices=[('nuvio', 'Nuvio'), ('simkl', 'Simkl'), ('trakt', 'Trakt')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='title',
            index=django.contrib.postgres.indexes.GinIndex(fields=['external_ids'], name='tracker_title_external_ids_gin'),
        ),
    ]
