# Generated by Django 5.2.16 on 2026-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_title_external_ids_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchprogress',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('planned', 'Planned'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=12),
        ),
    ]
