# Generated by Django 5.2.16 on 2026-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_watchprogress_dropped_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
