# Generated by Django 5.2.16 on 2026-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_watchlist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
