# Generated by Django 5.2.16 on 2026-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_profile_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_landing_page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('movies', 'Movies'), ('tv', 'TV'), ('anime', 'Anime'), ('history', 'History'), ('calendar', 'Calendar'), ('lists', 'Lists'), ('stats', 'Stats')], default='dashboard', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchevent',
            name='source',
            field=models.CharField(blank=True, choices=[('nuvio', 'Nuvio'), ('simkl', 'Simkl'), ('trakt', 'Trakt'), ('webhook', 'Scrobble API')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['profile', 'read'], name='tracker_not_profile_d75b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['to_profile', 'status'], name='tracker_rec_to_prof_c12e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='watchevent',
            index=models.Index(fields=['profile', 'title'], name='tracker_wat_profile_07287f_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['profile', 'status'], name='tracker_wat_profile_f3377b_idx'),
        ),
    ]
