# Generated by Django 5.2.16 on 2026-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_hot_path_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_release', 'New release'), ('upcoming_release', 'Upcoming release'), ('sync_failed', 'Sync failed'), ('system_update', 'System update'), ('recommendation_received', 'Recommendation received'), ('recommendation_watched', 'Recommendation watched'), ('watchlist_stale', 'Watchlist time capsule')], max_length=25),
        ),
    ]
