# Generated by Django 5.2.16 on 2026-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_profileachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
