# Generated by Django 5.2.16 on 2026-08-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_recommendation_is_blind_recommendation_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_genre_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_provider_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_region',
            field=models.CharField(default='US', max_length=2),
        ),
    ]
