# Generated by Django 5.2.16 on 2026-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0046_profile_preferred_genre_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animations_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
