# Generated by Django 5.2.16 on 2026-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_profile_animations_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='replied_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reply_message',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reply_reaction',
            field=models.CharField(blank=True, choices=[('interested', 'Interested 👀'), ('maybe_later', 'Maybe Later ⏳'), ('hard_pass', 'Hard Pass 🙅'), ('already_seen', 'Already Seen It 🍿'), ('say_less', 'Say Less 🫡'), ('bold_choice', 'Bold Choice 😏')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_release', 'New release'), ('upcoming_release', 'Upcoming release'), ('sync_failed', 'Sync failed'), ('system_update', 'System update'), ('recommendation_received', 'Recommendation received'), ('recommendation_watched', 'Recommendation watched'), ('recommendation_replied', 'Recommendation replied'), ('watchlist_stale', 'Watchlist time capsule')], max_length=25),
        ),
    ]
