# Generated by Django 5.2.16 on 2026-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_recommendation_replied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reply_reaction',
            field=models.CharField(blank=True, choices=[('watchlisting', 'Adding to Watchlist 👍'), ('already_seen', 'Already Seen It 😍'), ('excited', 'Excited 🔥'), ('not_for_me', 'Not For Me 😅')], default=None, max_length=20, null=True),
        ),
    ]
