# Generated by Django 5.2.16 on 2026-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0051_remove_profile_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(default='reports:read', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='encrypted_sso_shared_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='spool_wrapped_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrapped_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrapped_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrapped_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='title',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='title',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='title',
            name='directors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='title',
            name='network',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='title',
            name='studio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='title',
            name='writers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
