# Generated by Django 5.2.16 on 2026-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_serviceapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='imported_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='synclog',
            name='imported_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
