# Generated by Django 5.2.16 on 2026-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0053_datalog_imported_titles_synclog_imported_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='action',
            field=models.CharField(choices=[('import', 'CSV Import'), ('export', 'Export'), ('trakt_connect', 'Trakt Connect'), ('simkl_connect', 'Simkl Connect'), ('nuvio_connect', 'Nuvio Connect'), ('merge_duplicates', 'Merge Duplicate Titles'), ('backfill_posters', 'Backfill Posters'), ('backfill_genres', 'Backfill Genres'), ('backfill_completion', 'Backfill Completion'), ('backfill_rewatches', 'Backfill Rewatches'), ('disconnect', 'Disconnect'), ('mdblist_refresh', 'MDBList Refresh'), ('reclassify_anime', 'Reclassify Anime'), ('release_sync', 'Release Sync'), ('release_notifications', 'Release Notifications'), ('watchlist_stale', 'Watchlist Reminders'), ('update_check', 'Update Check'), ('log_retention', 'Log Retention')], max_length=25),
        ),
    ]
