# Generated by Django 5.2.17 on 2026-09-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0054_alter_datalog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gemini_api_key',
        ),
    ]
