# Generated by Django 5.2.17 on 2026-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0055_remove_profile_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totp_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
