# Generated by Django 5.2.17 on 2026-09-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0057_remove_stale_watch_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('trakt', 'Trakt'), ('simkl', 'Simkl'), ('nuvio', 'Nuvio'), ('csv', 'CSV'), ('json', 'JSON'), ('zip', 'ZIP')], max_length=10)),
                ('status', models.CharField(choices=[('scanning', 'Scanning'), ('ready', 'Ready for review'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='scanning', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('import_options', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('selected_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('imported_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('conflict_items', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='tracker.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('history', 'Watch history'), ('progress', 'Playback progress'), ('rating', 'Rating'), ('watchlist', 'Watchlist/list state')], max_length=10)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV'), ('anime', 'Anime')], max_length=10)),
                ('title_name', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('episode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('progress_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('list_name', models.CharField(blank=True, default='', max_length=100)),
                ('list_action', models.CharField(blank=True, default='', max_length=10)),
                ('source_external_ids', models.JSONField(blank=True, default=dict)),
                ('resolved_external_ids', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(blank=True, choices=[('create_title', 'Create new title'), ('link_provider_id', 'Link to existing title'), ('create_event', 'Log watch'), ('update_progress', 'Update progress'), ('update_rating', 'Update rating'), ('list_change', 'Change list membership'), ('noop_duplicate', 'Already in Spool')], default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('conflict_type', models.CharField(blank=True, default='', max_length=30)),
                ('conflict_data', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(blank=True, choices=[('keep_spool', "Keep Spool's value"), ('use_imported', 'Use imported value'), ('skip', 'Skip this item')], default='', max_length=15)),
                ('warning', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('matched_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_candidates', to='tracker.title')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='tracker.importsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['profile', 'status'], name='tracker_imp_profile_5e0788_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['status', 'expires_at'], name='tracker_imp_status_9c214d_idx'),
        ),
        migrations.AddIndex(
            model_name='importcandidate',
            index=models.Index(fields=['import_session', 'status'], name='tracker_imp_import__248b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='importcandidate',
            index=models.Index(fields=['import_session', 'category', 'status'], name='tracker_imp_import__fe4c72_idx'),
        ),
    ]
